services:
  app:
    build: .
    container_name: russian-asr-itn-hybrid
    volumes:
      - ./data:/app/data
      - ./answer.f:/app/answer.f
      - ./reports:/app/reports
    stdin_open: true
    tty: true
